In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
x=np.array([1,2,3])
x.size #array size

3

In [6]:
arr=np.array([[1,2,3],[4,5,6]])
arr.shape #gives array shape

(2, 3)

In [10]:
a=np.array([1,2,3],[4,7,8]])
print(a.ndim) #dimension of the array
print(a.nbytes) #byte size of each element

2
48


In [15]:
arr=np.array([[1,3,45],[3,7,1]])
print(arr.dtype) #data types of elements

int64


In [16]:
arr=np.array([1,2,4,5],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'4' b'5']
|S1


In [17]:
arr=np.array([1,2,4,5],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 4 5]
int32


In [25]:
a=[34,73,24,8,35]
b=a[1:4] #slicing
c=a[2:5]
print("b=",b)
print("c=",c)

b= [73, 24, 8]
c= [24, 8, 35]


In [27]:
arr=[34,67,25,87]
print(np.std(arr)) #standard deviation

24.983744715314394


In [28]:
arr=np.array([1,2,3])
print(np.log10(arr)) #returns the logarithm value 

[0.         0.30103    0.47712125]


In [30]:
np.sqrt(625) #square root value

25.0

In [32]:
x=np.array([[1,2,6],[34,78,3]])
y=np.array([[34,83,68],[256,46,35]])
print("addition=",np.add(x,y))
print("subtraction=",np.subtract(x,y))
print("multiplication=",np.multiply(x,y))
print("division=",np.divide(x,y))

addition= [[ 35  85  74]
 [290 124  38]]
subtraction= [[ -33  -81  -62]
 [-222   32  -32]]
multiplication= [[  34  166  408]
 [8704 3588  105]]
division= [[0.02941176 0.02409639 0.08823529]
 [0.1328125  1.69565217 0.08571429]]


In [38]:
arr1=np.zeros((3,3)) #creates a matrix full of zeros
arr2=np.ones((4,4))#creates a matrix full of ones
print("zeros 3x3=",arr1)
print("ones 4x4=",arr2)

zeros 3x3= [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones 4x4= [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [40]:
a1=np.array([2,5,8])
a2=np.array([3,5,7])
a3=np.concatenate((a1,a2)) #join arrays, default axis=0
print(a3)

[2 5 8 3 5 7]


In [41]:
a1=np.array([[2,5,8],[33,5,7]])
a2=np.array([[3,5,7],[45,73,7]])
a3=np.concatenate((a1,a2),axis=1) #join arrays,axis=1
print(a3)

[[ 2  5  8  3  5  7]
 [33  5  7 45 73  7]]


In [43]:
a1=np.array([[2,5,8],[33,5,7]])
a2=np.array([[3,5,7],[45,73,7]])
a3=np.stack((a1,a2),axis=1) #similar to concatenate but is done along a new axis and stack one over the other.
print(a3)

[[[ 2  5  8]
  [ 3  5  7]]

 [[33  5  7]
  [45 73  7]]]
